export const SUPPORT_EMAIL_ALERT_SCHEMA_VERSION = 1 as const;

export const SUPPORT_EMAIL_ALERT_QUIET_PERIOD_MILLISECONDS =
  5 * 60 * 1_000;

export const SUPPORT_EMAIL_ALERT_WORKER_INTERVAL_MILLISECONDS =
  30 * 1_000;

export const SUPPORT_EMAIL_ALERT_LEASE_MILLISECONDS =
  2 * 60 * 1_000;

export const SUPPORT_EMAIL_ALERT_MAX_BATCHES_PER_PASS = 10;

export const SUPPORT_EMAIL_ALERT_RETRY_BASE_MILLISECONDS =
  60 * 1_000;

export const SUPPORT_EMAIL_ALERT_RETRY_MAX_MILLISECONDS =
  15 * 60 * 1_000;
